# Generated by Django 4.0.1 on 2022-01-27 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 1, 27, 20, 16, 48, 809528), verbose_name='date of birthd'),
        ),
    ]
