# Generated by Django 4.0.1 on 2022-01-28 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 1, 28, 15, 23, 28, 452815), verbose_name='date of birthd'),
        ),
    ]
