# Generated by Django 4.0.1 on 2022-02-02 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 9, 32, 3, 784839), verbose_name='date of birthd'),
        ),
    ]
