# Generated by Django 4.0.1 on 2022-02-02 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 12, 39, 1, 250281), verbose_name='date of birthd'),
        ),
    ]
