# Generated by Django 4.0.1 on 2022-02-03 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 2, 3, 12, 59, 4, 724988), verbose_name='date of birthd'),
        ),
    ]
