# Generated by Django 3.1.14 on 2022-01-25 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 48, 43, 426349), verbose_name='date published'),
        ),
    ]
