# Generated by Django 3.1.14 on 2022-01-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='question',
            name='module',
        ),
    ]