# Generated by Django 3.1.14 on 2022-01-24 13:02

import catalog.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220123_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, upload_to=catalog.models.save_rename_question, verbose_name='Question Attachment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 13, 2, 45, 358747), verbose_name='date published'),
        ),
    ]
