# Generated by Django 4.0.1 on 2022-01-29 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 1, 29, 12, 39, 18, 292316), verbose_name='date of birthd'),
        ),
    ]
