# Generated by Django 3.1.14 on 2022-01-25 11:03

import curriculum.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('duedate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.TextField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=curriculum.models.course_rename, verbose_name='Course Image')),
                ('course_description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(choices=[('Assignment Related', 'Assignment Related'), ('Lecture Related', 'Lecture Related'), ('General', 'General')], default='General', max_length=20)),
                ('subject', models.TextField(max_length=100, null=True)),
                ('question', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 1, 25, 11, 3, 26, 599849), verbose_name='date published')),
                ('picture', models.ImageField(blank=True, upload_to=curriculum.models.save_rename_question, verbose_name='Question Attachment')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('status', models.CharField(max_length=255)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.question')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('module_name', models.TextField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='curriculum.course')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.standard')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lecture_title', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Chapter no.')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('slides', models.FileField(blank=True, upload_to=curriculum.models.save_lecture_slides, verbose_name='Lecture Slides')),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='curriculum.course')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.standard')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assignment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.assignment')),
                ('module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.module')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='curriculum.standard'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curriculum.module'),
        ),
    ]
