# Generated by Django 4.0.1 on 2022-01-27 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_rename_course_description_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 9, 45, 52, 563342), verbose_name='date published'),
        ),
    ]
