# Generated by Django 4.0.1 on 2022-01-27 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_question_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='module_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 10, 56, 25, 953285), verbose_name='date published'),
        ),
    ]
