# Generated by Django 4.0.1 on 2022-01-27 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_rename_module_name_module_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 10, 58, 46, 322022), verbose_name='date published'),
        ),
    ]
