# Generated by Django 4.0.1 on 2022-01-27 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_alter_question_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='curriculum.assignment'),
        ),
        migrations.AddField(
            model_name='question',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='curriculum.lecture'),
        ),
        migrations.AddField(
            model_name='question',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='curriculum.module'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 11, 38, 27, 44540), verbose_name='date published'),
        ),
    ]
