# Generated by Django 4.0.1 on 2022-01-27 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_alter_question_created_at_alter_question_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 15, 45, 55, 955425), verbose_name='date published'),
        ),
    ]
