# Generated by Django 4.0.1 on 2022-01-28 19:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0024_alter_question_created_at_alter_question_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answer_body',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='comment_name',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='curriculum.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 19, 52, 23, 164131), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
