# Generated by Django 4.0.1 on 2022-02-02 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0029_assignment_lecture_remove_reply_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='curriculum.module'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 11, 54, 48, 165936), verbose_name='date published'),
        ),
    ]
