# Generated by Django 4.0.1 on 2022-02-03 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0032_alter_question_created_at_alter_question_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 12, 59, 4, 723087), verbose_name='date published'),
        ),
    ]
